
-- Remove obsolete patch tables
DROP TABLE IF EXISTS patch_logs CASCADE;
DROP TABLE IF EXISTS patch_diffs CASCADE; 
DROP TABLE IF EXISTS patch_releases CASCADE;
DROP TABLE IF EXISTS file_baselines CASCADE;
DROP TABLE IF EXISTS overlay_snapshots CASCADE;
DROP TABLE IF EXISTS code_overlays CASCADE;
DROP TABLE IF EXISTS hybrid_patches CASCADE;
DROP TABLE IF EXISTS ast_diffs CASCADE;

